name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generating svg
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contr-grid-snake.svg?color_snake=#d5c3f0&color_dots=#60596b,#837596,#8e7bab,#ab93cf,#b99fe0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pushing svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
